# Generated by Django 4.1.3 on 2023-06-21 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='images/')),
                ('text', models.CharField(max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('text', models.TextField()),
                ('buy_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('text', models.CharField(max_length=500)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('categoriya', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='main.categoriya')),
            ],
        ),
    ]
