# Generated by Django 4.1.3 on 2023-06-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_categoriya_sotilganlar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriya',
            name='sotilganlar',
        ),
    ]
