# Generated by Django 4.2.2 on 2023-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_categoriya_sotilganlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriya',
            name='img',
            field=models.ImageField(upload_to='product/'),
        ),
    ]
